language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: 5.5

services:
  - mongodb

before_script:
  - phpenv config-add tests/config/php.ini
  - php -m
  - php -i
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --prefer-source --no-interaction
  - mysql -e 'CREATE DATABASE IF NOT EXISTS widget_tests;'
  - psql -c 'CREATE DATABASE widget_tests;' -U postgres
  - mkdir -p build/logs

script:
  - phpunit --verbose --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v --exclude-no-stmt