language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

services:
  - mongodb
  - memcached
  - redis-server

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
  - pecl install redis
  - sh -c 'if [ $(php -r "echo PHP_MINOR_VERSION;") -gt 4 ]; then sed -i 1d "tests/config/php.ini"; fi;'
  - phpenv config-add tests/config/php.ini
  - mysql -e 'CREATE DATABASE IF NOT EXISTS wei_tests;'
  - psql -c 'CREATE DATABASE wei_tests;' -U postgres
  - mkdir -p build/logs
  - sh -c 'if [ $(php -r "echo PHP_MINOR_VERSION;") -gt 3 ]; then php -S 0.0.0.0:8000 -t tests/unit/Fixtures/; fi;' > /dev/null &

script:
  - phpunit --verbose --coverage-clover build/logs/clover.xml

after_script:
  - pkill php
  - php vendor/bin/coveralls -v --exclude-no-stmt