language: php

php:
  - 5.3
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: 5.5
   
# Let phpunit generate the code coverage report in the clover format
script: 
  - phpunit --coverage-clover "clover"

after_success:
    - curl -sL https://bit.ly/artifact-uploader | php