# Configuration for wei container
wei:
  inis:
    error_reporting: 0
    display_errors: off
  debug: false
  # More option for wei container here ...
# Configuration for logger wei
logger:
  dir: log
# More configuration for other weis here ...