# Configuration for wei container
wei:
  inis:
    error_reporting: -1
    display_errors: on
  debug: true
  # More option for wei container here ...
# Configuration for logger wei
logger:
  dir: log
# More configuration for other weis here ...