# Configuration for widget container
widget:
  inis:
    error_reporting: -1
    display_errors: on
  debug: true
  # More option for widget container here ...
# Configuration for logger widget
logger:
  dir: log
# More configuration for other widgets here ...