# Configuration for widget container
widget:
  inis:
    error_reporting: 0
    display_errors: off
  debug: false
  # More option for widget container here ...
# Configuration for logger widget
logger:
  dir: log
# More configuration for other widgets here ...